import i18n from "i18next";
import { initReactI18next } from "react-i18next";
const resources = {
  en: {
    translation: {
      Historia: "History",
      Frakcje: "Fractions",
      Posty: "Posts",
      "Dodaj post": "Add post",
      Tytuł: "Title",
      Autor: "Author",
      Opis: "Description",
      Dodaj: "Add",
      "Według wczesnej mitologii Krasnoludów , Elfów i Jaszczuroludzi - miliony lat temu na ziemię przybyła rasa istot, znanych teraz jako Pradawni (Prastarzy). Były to dziwne stworzenia o niemal boskich mocach. Ukształtowały one klimat i teren tego świata. Uważano, że nie pochodzą z tego świata, lecz byli także jego twórcami. Nowo odkryty świat wydał im się dobry. Wiedzieli, że odegra główną rolę w historii wszechświata, postanowili więc pokierować jego drogą. Ogrzali go w promieniach słońca i wykuli kontynenty zgodnie z wzorami starożytnego proroctwa. Aby ułatwić sobie prace, stworzyli Portale Biegunowe na północnej i południowej granicy świata. Pozwoliły one na błyskawiczne podróżowanie przez rozległe przestrzenie dzielące ich skolonizowane światy.":
        "According to the early mythology of Dwarves, Elves and Lizardmen millions of years ago a race of beings came to earth, now known as the Ancients. They were strange creatures with almost divine powers. They shaped the climate and terrain of this world. It was believed that they did not come from this world, but were also its creators. The newly discovered world seemed good to them. They knew he would play a major role in the history of the universe, so they decided to steer his path. They warmed it in the rays of the sun and forged continents according to the patterns of ancient prophecy. To facilitate their work, they created Polar Portals on the northern and southern border of the world. They allowed them to travel rapidly through the vast spaces separating their colonized worlds.",
      "Później pradawni mieli zapłacić za swoje aroganckie wtargnięcie. Stworzone przez nich Bramy Wypaczenia na biegunach świata, każda przyćmiewająca największe góry, zostały zniszczone, jako że duchy znajdujące się w krainie za zasłoną skręcały się i gotowały wraz ze zmieniającym się światem żywych. Bramy Wypaczenia zapadły się w przełomowej dla epoki eksplozji, dewastującej kontynenty i zalewającej świat, wraz z konstrukcjami pradawnych, ogromnymi, gotującymi się morzami Chaosu. Zatarła się przez to granica pomiędzy rzeczywistością, a światem niematerialnym i zaczęły się one na siebie nakładać. Hordy demonicznych kreatur natarły na świat i wymordowały Pradawnych, niszcząc doszczętnie ich prosperującą do tej pory cywilizację .":
        "Later the ancients were to pay for their arrogant intrusion. Their Gates of Warpping at the poles of the world, each overshadowing the greatest mountains, were destroyed as the spirits within the land beyond the veil twisted and cooked with the changing world of the living. The Gates of Warp have collapsed in a landmark explosion for the age, devastating continents and flooding the world, along with the structures of the ancient, huge, boiling seas of Chaos. As a result, the border between reality and the non-material world has blurred and they began to overlap. Hordes of demonic creatures invaded the world and slaughtered the Ancients, destroying their hitherto prospering civilization.",
      "Świat Warhammera mieści się na planecie, której powierzchnia jest pokryta kilkoma wielkimi kontynentami, z któych każdy posiada odrębną cywilizację i zróżnicowaną faunę. Wokół planety krążą dwa księżyce - biało-szary Mannslieb i zielonkawy Morrslieb, o który mówi się, że jest wielką grudą spaczenia, która znalazła się w atmosferze dawno temu, kiedy Bramy Wypaczenia upadły i zaczęły wylewać Chaos na ziemię. Aktualnie na planecie rządzi rasa ludzi, głównie z Imperium w Starym Świecie, utworzone przez Sigmara Młotodzierżce z niezliczonych walczących między sobą plemion terenu znanego jako Dorzecze Reiku, które urosło do prawie niedostępnego globalnego mocarstwa. Imperium jest najeżdżane ze wszystkich stron - z zimnej północy nadciąga groźny Chaos, ze wschodu hordy Zielonoskórych .Natomiast wewnętrzna niespójność kala chwałę imperium Sigmara i rozkłada je od środka.":
        "The world of Warhammer resides on a planet whose surface is covered by several great continents, each with a distinct civilization and diverse fauna. Two moons orbit the planet - the white-gray Mannslieb and the greenish Morrslieb, which is said to be the great lump of corruption that entered the atmosphere long ago when the Warp Gates fell and began pouring Chaos to the ground. Currently, the planet is ruled by a race of people, mainly from the Empire in the Old World, formed by Sigmar the Hammerhead from countless fighting tribes of the area known as the Reiku Basin, which has grown into an almost inaccessible global power. The empire is raided from all sides - the menacing Chaos is coming from the cold north, the Greenskin hordes from the east, while internal inconsistency defiles the Sigmar's empire and tears it apart from the inside.",
      Tyranidzi: "Tyranids",
      "Po raz pierwszy w historii Drogi Mlecznej pojawiają się siły z innych galaktyk. To Tyranidzi, niby zwiastun końca. Wszystko żrą, ogałacają całe planety i rozmnażają się i tak w kółko. Jak rurkowce. Nie stosują technologii, są mistrzami ewolucji i adaptacji genów. Ich ilość jest nieporównywalna do wszystkich ras razem wziętych i pomnożonych przez niewiadomo ile. Jakościowo jednostki mają lepsze niż większość innych frakcji, ale o bardzo małym potencjale destrukcyjnym, niby pożerają dużo planet ale w najważniejszych konfliktach zawsze dostają baty i przeciw nim nawet wrogowie łączą siły.":
        "For the first time in the history of the Milky Way, forces from other galaxies appear. They are the Tyranids, like a harbinger of the end. They eat everything, strip entire planets, and keep reproducing over and over again. Like tubers. They don't use technology, they are masters of gene evolution and adaptation. Their number is incomparable to all races combined and multiplied by unknown how many. Qualitatively, units are better than most other factions, but with very little destructive potential, as if they eat a lot of planets, but in the most important conflicts they always get whips and even enemies join forces against them.",
      Nekroni: "Necrons",
      "Oprócz tego nieco wcześniej budzą się do życia starożytne maszyny, które 60 milionów lat temu rządziły Galaktyką, powstają by odzyskać władze a nawet coś więcej - duszę i ciała. To Nekroni, przeciwnik o niezwykle zaawansowanej technologii i często jest po prostu przepotężny wobec innych wojsk galaktyki. Dawno dawno temu byli normalnymi istotami, ale zaprzedali dusze dla nieśmiertelności, stając się maszynami - proces, który część z nich próbuje odwrócić. Teoretycznie ich władcą jest Milczący Król, który powrócił do Galaktyki po tułaczce by znów postawić swoją rasę na mechaniczne nogi.":
        "In addition, the ancient machines that ruled the Galaxy 60 million years ago come to life slightly earlier, they arise to regain power and even something more - soul and body. He is the Nekroni, an adversary with extremely high technology, and is often simply powerful against the other forces in the galaxy. Once upon a time they were normal beings, but they sold their souls for immortality, becoming machines - a process some of them are trying to reverse. Theoretically, their ruler is the Silent King, who returned to the Galaxy after wandering to put his race on mechanical legs again.",
      Orkowie: "Orcs",
      "Bardzo silni i trudni w eksterminacji obcy. Złomiarze. Ich technologia działa bo... bo oni chcą żeby tak było, to tzw. orkowość / orkowa energia. Oprócz tego wojna to dla nich tylko i wyłącznie rozrywka i sport, rozmnażają się jak grzyby po deszczu, dosłownie - to grzyby. Istnieją też odmiany Orków nie znające technologii. Latają od planet do planet i robią WAAAAGH! Są bardzo mocno podzieleni, nie stanowią jednolitej grupy i bardzo często walczą sami ze sobą tylko i wyłącznie dla własnej uciechy, obecnie największe WAAAAGH! przeprowadza Ghazghkull Mag Uruk Thraka.":
        "Very strong and difficult to exterminate aliens. Scrap collectors. Their technology works because ... because they want it to be so, it's the so-called orcish / orcish energy. In addition, war is only entertainment and sport for them, they reproduce like mushrooms after rain, literally - they are mushrooms. There are also varieties of Orcs that do not know the technology. They fly from planets to planets and do WAAAAGH! They are very divided, they do not constitute a homogeneous group and very often they fight with each other only for their own amusement, currently the biggest WAAAAGH! carried out by Ghazghkull Mage Uruk Thraka.",
      Eldarzy: "Eldars",
      "Ci którzy na statkach wielkości małych planet uciekli przed upadkiem swojej rasy. W ich skład obok zwykłych, zamieszkujących owe światostatki wchodzą też Wygnańcy, którzy jeszcze przed upadkiem Eldarów woleli odłączyć się od reszty swych braci. Enigmatyczni Arlekini, zamieszkujący Pajęczy Trakt (inny wymiar), działają dla Roześmianego Boga (bóg Eldarów, jeden z niewielu który przeżył narodziny Slaanesha). Są też Wyrzutki, którzy opuścili światostatek i tułają się bez celu po Galaktyce, są Uciekinierzy, którzy, cóż uciekli i od dawna żyją sobie na dziewiczych światach. Ogólnie Eldarzy to rasa psioników, którzy mocami Osnowy mogą wpływać na rzeczywistość. Coś jak magia, ale to nie magia. Bardzo enigmatyczna rasa, która stara się ingerować w ważne wydarzenia w galaktyce, nierzadko ratując/zabijając wiele istnień przed Chaosem etc.":
        "Those who fled from the fall of their race on ships the size of small planets. In addition to the ordinary, inhabiting these world ships, they also include the Exiles who, even before the fall of the Eldar, preferred to separate from the rest of their brothers. The enigmatic Harlequins inhabiting the Spider Road (other dimension) work for the Laughing God (god of the Eldar, one of the few who survived the birth of Slaanesh). There are also Outcasts who have left the world ship and wander aimlessly in the Galaxy, there are Fugitives who, well, have escaped and have lived on virgin worlds for a long time. Overall, the Eldar are a race of psionics who can influence reality with the powers of the Warp. Something like magic, but it's not magic. A very enigmatic race that tries to interfere with important events in the galaxy, often saving / killing many lives from Chaos etc.",
      "Mroczni Eldarzy": "Dark Eldars",
      "Bracia wyżej wymienionych Eldarów, którzy również przetrwali, jednak są hedonistycznymi i zdeprawowanymi emo. To głównie piraci latający sobie od planetki do planetki zbierając niewolników i ciekawych Xenos do uprawiania bardzo niefajnych rzeczy ( ͡° ͜ʖ ͡°). Uwielbiają politykę, czyli wbijanie sobie sztyletów w plecy. Nie mają psioników, ich zbroje to ich skóra i kości, bowiem polegają na zwinności i mobilności, nawet bardziej niż ich kuzyni. Mroczni Eldarzy mimo iż mroczni nie wyznają Bogów Chaosu, jeśli już to wszelkie ich działania podyktowane są strachem przed Slaanesh.":
        "The brothers of the above-mentioned Eldar who also survive, however, are hedonistic and depraved emo. They are mostly pirates flying from planet to planet collecting slaves and interesting Xenos to do very bad things (͡ ° ͜ʖ ͡ °). They love politics, which is sticking daggers in the back. They have no psykers, their armor is their skin and bones, for they rely on agility and mobility even more than their cousins. Dark Eldars, although the dark ones do not confess to Chaos Gods, if all their actions are dictated by the fear of Slaanesh.",
      "Dominium Tau": "Dominion of Tau",
      "Prócz tego mamy jeszcze młode i prężnie rozwijające się, a także jako jedyne asymilujące, a nie eksterminujące inne gatunki Dominium Tau. To rasa walcząca dla Większego Dobra, właściwie najbardziej dobra ze wszystkich ras. Ich technologia skupia się na maskowaniach, mobilności i sile ognia - coś jak dzisiejsze wojsko. Wykorzystują pancerze bitewne - humanoidalne maszyny sterowane przez pilotów. Nie potrafią walczyć wręcz. Osobną frakcją są stworzone przez renegata z Dominium Tau tzw. Enklawy Farsighta, od nazwy buntownika. Należy pamiętać że Dominium i Enklawy są bardzo malutkie i nie mają aż takiego wpływu na sytuacje w Galaktyce ale szybko ekspandują":
        "Apart from that, we still have young and dynamically developing species, as well as the only ones that assimilate and not exterminate other species of the Tau Dominion. It is a race fighting for the Greater Good, actually the best of all races. Their technology focuses on masking, mobility and firepower - something like today's military. They use battle armor - humanoid machines controlled by pilots. They cannot fight hand-to-hand. A separate faction are the so-called Farsight's enclaves, from the name of the rebel. Remember that the Dominion and Enclaves are very tiny and do not have such an impact on the situation in the Galaxy but they expand quickly",
      Chaos: "Chaos",
      "W jego skład wchodzą jego wyznawcy, w postaci ludzi(najczęściej) czy innych obcych (np. bardzo rzadko Orkowie, czyniektórzy Eldarzy) oraz masa demonów i sił jeszcze z czasówHerezji Horusa. Są bardzo podzieleni a największym dowódcą siłjest Abaddon Profanator, zaś prawdziwi władcy tej frakcji -Mroczni Bogowie przebywają w innym wymiarze, Osnowie, gdzie sąwyłącznie emocje, uczucia i dusze, nie ma praw fizyki a konceptczasu wziął i wyszedł. Występuje tam niezliczona ilość demonów,wszystko tam jest wypaczone, czas nie istnieje itd. To dziękiOsnowie wszystkie rasy (poza Nekronami, bo używają innejtechnologii) mogą latać szybciej niż światło. Istnieje 4 bogów,docelowo 5. Tzeentch odpowiada za magię (psionizm) i knowania.Nurgle za choroby i śmierć. Khorne za przelewanie krwi. Slaaneshza hedonizm, przyjemności, czy seksualne żądze. I Malice(prawdopodobnie nie istnieje/jest niekanoniczny), wygnany przezresztę bogów bóg szaleństwa, bardzo słaby, nikt go nie lubi i wdodatku prawie nie ma armii (1 zakon, Synowie Malice i dlategojest plotka jakoby istniał - głównie dzieło fanów znającychWarhammera Fantasy, aczkolwiek nie został też zanegowany.)":
        "It consists of his followers, in the form of people (most often) or other strangers (e.g. very rarely Orcs, or some Eldar) and a mass of demons and forces from the time of the Horus Heresy. They are very divided and the greatest commander of the forces is Abaddon the Profanator, and the true rulers of this faction - the Dark Gods reside in another dimension, the Warp, where there are only emotions, feelings and souls, there are no laws of physics and the concept of time took and left. There are countless demons there, everything is warped there, time does not exist, etc. It is thanks to Osna that all races (except the Necrons, because they use different technology) can fly faster than light. There are 4 gods, ultimately 5. Tzeentch is responsible for magic (psionism) and plotting. Nurgle for disease and death. Khorne for shedding blood. Slaaneshz hedonism, pleasures, or sexual desires. And Malice (probably does not exist / is non-canonical), god of madness exiled by the other gods, very weak, nobody likes him and additionally has almost no army (1st order, Sons of Malice and therefore there is a rumor that he exists - mainly the work of fans who know Warhammer Fantasy, although not was also denied.)",
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: "pl",
  fallbackLng: "pl",
  keySeparator: false,

  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
