import i18n from "i18next";
import { initReactI18next } from "react-i18next";
const resources = {
  en: {
    translation: {
      Historia: "History",
      Frakcje: "Fractions",
      Posty: "Posts",
      "Dodaj post": "Add post",
      Tytuł: "Title",
      Autor: "Author",
      Opis: "Description",
      Dodaj: "Add",
      "Według wczesnej mitologii Krasnoludów , Elfów i Jaszczuroludzi - miliony lat temu na ziemię przybyła rasa istot, znanych teraz jako Pradawni (Prastarzy). Były to dziwne stworzenia o niemal boskich mocach. Ukształtowały one klimat i teren tego świata. Uważano, że nie pochodzą z tego świata, lecz byli także jego twórcami. Nowo odkryty świat wydał im się dobry. Wiedzieli, że odegra główną rolę w historii wszechświata, postanowili więc pokierować jego drogą. Ogrzali go w promieniach słońca i wykuli kontynenty zgodnie z wzorami starożytnego proroctwa. Aby ułatwić sobie prace, stworzyli Portale Biegunowe na północnej i południowej granicy świata. Pozwoliły one na błyskawiczne podróżowanie przez rozległe przestrzenie dzielące ich skolonizowane światy.":
        "According to the early mythology of Dwarves, Elves and Lizardmen millions of years ago a race of beings came to earth, now known as the Ancients. They were strange creatures with almost divine powers. They shaped the climate and terrain of this world. It was believed that they did not come from this world, but were also its creators. The newly discovered world seemed good to them. They knew he would play a major role in the history of the universe, so they decided to steer his path. They warmed it in the rays of the sun and forged continents according to the patterns of ancient prophecy. To facilitate their work, they created Polar Portals on the northern and southern border of the world. They allowed them to travel rapidly through the vast spaces separating their colonized worlds.",
      "Później pradawni mieli zapłacić za swoje aroganckie wtargnięcie. Stworzone przez nich Bramy Wypaczenia na biegunach świata, każda przyćmiewająca największe góry, zostały zniszczone, jako że duchy znajdujące się w krainie za zasłoną skręcały się i gotowały wraz ze zmieniającym się światem żywych. Bramy Wypaczenia zapadły się w przełomowej dla epoki eksplozji, dewastującej kontynenty i zalewającej świat, wraz z konstrukcjami pradawnych, ogromnymi, gotującymi się morzami Chaosu. Zatarła się przez to granica pomiędzy rzeczywistością, a światem niematerialnym i zaczęły się one na siebie nakładać. Hordy demonicznych kreatur natarły na świat i wymordowały Pradawnych, niszcząc doszczętnie ich prosperującą do tej pory cywilizację .":
        "Later the ancients were to pay for their arrogant intrusion. Their Gates of Warpping at the poles of the world, each overshadowing the greatest mountains, were destroyed as the spirits within the land beyond the veil twisted and cooked with the changing world of the living. The Gates of Warp have collapsed in a landmark explosion for the age, devastating continents and flooding the world, along with the structures of the ancient, huge, boiling seas of Chaos. As a result, the border between reality and the non-material world has blurred and they began to overlap. Hordes of demonic creatures invaded the world and slaughtered the Ancients, destroying their hitherto prospering civilization.",
      "Świat Warhammera mieści się na planecie, której powierzchnia jest pokryta kilkoma wielkimi kontynentami, z któych każdy posiada odrębną cywilizację i zróżnicowaną faunę. Wokół planety krążą dwa księżyce - biało-szary Mannslieb i zielonkawy Morrslieb, o który mówi się, że jest wielką grudą spaczenia, która znalazła się w atmosferze dawno temu, kiedy Bramy Wypaczenia upadły i zaczęły wylewać Chaos na ziemię. Aktualnie na planecie rządzi rasa ludzi, głównie z Imperium w Starym Świecie, utworzone przez Sigmara Młotodzierżce z niezliczonych walczących między sobą plemion terenu znanego jako Dorzecze Reiku, które urosło do prawie niedostępnego globalnego mocarstwa. Imperium jest najeżdżane ze wszystkich stron - z zimnej północy nadciąga groźny Chaos, ze wschodu hordy Zielonoskórych .Natomiast wewnętrzna niespójność kala chwałę imperium Sigmara i rozkłada je od środka.":
        "The world of Warhammer resides on a planet whose surface is covered by several great continents, each with a distinct civilization and diverse fauna. Two moons orbit the planet - the white-gray Mannslieb and the greenish Morrslieb, which is said to be the great lump of corruption that entered the atmosphere long ago when the Warp Gates fell and began pouring Chaos to the ground. Currently, the planet is ruled by a race of people, mainly from the Empire in the Old World, formed by Sigmar the Hammerhead from countless fighting tribes of the area known as the Reiku Basin, which has grown into an almost inaccessible global power. The empire is raided from all sides - the menacing Chaos is coming from the cold north, the Greenskin hordes from the east, while internal inconsistency defiles the Sigmar's empire and tears it apart from the inside.",
      Tyranidzi: "Tyranids",
      "Po raz pierwszy w historii Drogi Mlecznej pojawiają się siły z innych galaktyk. To Tyranidzi, niby zwiastun końca. Wszystko żrą, ogałacają całe planety i rozmnażają się i tak w kółko. Jak rurkowce. Nie stosują technologii, są mistrzami ewolucji i adaptacji genów. Ich ilość jest nieporównywalna do wszystkich ras razem wziętych i pomnożonych przez niewiadomo ile. Jakościowo jednostki mają lepsze niż większość innych frakcji, ale o bardzo małym potencjale destrukcyjnym, niby pożerają dużo planet ale w najważniejszych konfliktach zawsze dostają baty i przeciw nim nawet wrogowie łączą siły.":
        "For the first time in the history of the Milky Way, forces from other galaxies appear. They are the Tyranids, like a harbinger of the end. They eat everything, strip entire planets, and keep reproducing over and over again. Like tubers. They don't use technology, they are masters of gene evolution and adaptation. Their number is incomparable to all races combined and multiplied by unknown how many. Qualitatively, units are better than most other factions, but with very little destructive potential, as if they eat a lot of planets, but in the most important conflicts they always get whips and even enemies join forces against them.",
      Nekroni: "Necrons",
      "Oprócz tego nieco wcześniej budzą się do życia starożytne maszyny, które 60 milionów lat temu rządziły Galaktyką, powstają by odzyskać władze a nawet coś więcej - duszę i ciała. To Nekroni, przeciwnik o niezwykle zaawansowanej technologii i często jest po prostu przepotężny wobec innych wojsk galaktyki. Dawno dawno temu byli normalnymi istotami, ale zaprzedali dusze dla nieśmiertelności, stając się maszynami - proces, który część z nich próbuje odwrócić. Teoretycznie ich władcą jest Milczący Król, który powrócił do Galaktyki po tułaczce by znów postawić swoją rasę na mechaniczne nogi.":
        "In addition, the ancient machines that ruled the Galaxy 60 million years ago come to life slightly earlier, they arise to regain power and even something more - soul and body. He is the Nekroni, an adversary with extremely high technology, and is often simply powerful against the other forces in the galaxy. Once upon a time they were normal beings, but they sold their souls for immortality, becoming machines - a process some of them are trying to reverse. Theoretically, their ruler is the Silent King, who returned to the Galaxy after wandering to put his race on mechanical legs again.",
      Orkowie: "Orcs",
      "Bardzo silni i trudni w eksterminacji obcy. Złomiarze. Ich technologia działa bo... bo oni chcą żeby tak było, to tzw. orkowość / orkowa energia. Oprócz tego wojna to dla nich tylko i wyłącznie rozrywka i sport, rozmnażają się jak grzyby po deszczu, dosłownie - to grzyby. Istnieją też odmiany Orków nie znające technologii. Latają od planet do planet i robią WAAAAGH! Są bardzo mocno podzieleni, nie stanowią jednolitej grupy i bardzo często walczą sami ze sobą tylko i wyłącznie dla własnej uciechy, obecnie największe WAAAAGH! przeprowadza Ghazghkull Mag Uruk Thraka.":
        "Very strong and difficult to exterminate aliens. Scrap collectors. Their technology works because ... because they want it to be so, it's the so-called orcish / orcish energy. In addition, war is only entertainment and sport for them, they reproduce like mushrooms after rain, literally - they are mushrooms. There are also varieties of Orcs that do not know the technology. They fly from planets to planets and do WAAAAGH! They are very divided, they do not constitute a homogeneous group and very often they fight with each other only for their own amusement, currently the biggest WAAAAGH! carried out by Ghazghkull Mage Uruk Thraka.",
      Eldarzy: "Eldars",
      "Ci którzy na statkach wielkości małych planet uciekli przed upadkiem swojej rasy. W ich skład obok zwykłych, zamieszkujących owe światostatki wchodzą też Wygnańcy, którzy jeszcze przed upadkiem Eldarów woleli odłączyć się od reszty swych braci. Enigmatyczni Arlekini, zamieszkujący Pajęczy Trakt (inny wymiar), działają dla Roześmianego Boga (bóg Eldarów, jeden z niewielu który przeżył narodziny Slaanesha). Są też Wyrzutki, którzy opuścili światostatek i tułają się bez celu po Galaktyce, są Uciekinierzy, którzy, cóż uciekli i od dawna żyją sobie na dziewiczych światach. Ogólnie Eldarzy to rasa psioników, którzy mocami Osnowy mogą wpływać na rzeczywistość. Coś jak magia, ale to nie magia. Bardzo enigmatyczna rasa, która stara się ingerować w ważne wydarzenia w galaktyce, nierzadko ratując/zabijając wiele istnień przed Chaosem etc.":
        "Those who fled from the fall of their race on ships the size of small planets. In addition to the ordinary, inhabiting these world ships, they also include the Exiles who, even before the fall of the Eldar, preferred to separate from the rest of their brothers. The enigmatic Harlequins inhabiting the Spider Road (other dimension) work for the Laughing God (god of the Eldar, one of the few who survived the birth of Slaanesh). There are also Outcasts who have left the world ship and wander aimlessly in the Galaxy, there are Fugitives who, well, have escaped and have lived on virgin worlds for a long time. Overall, the Eldar are a race of psionics who can influence reality with the powers of the Warp. Something like magic, but it's not magic. A very enigmatic race that tries to interfere with important events in the galaxy, often saving / killing many lives from Chaos etc.",
      "Mroczni Eldarzy": "Dark Eldars",
      "Bracia wyżej wymienionych Eldarów, którzy również przetrwali, jednak są hedonistycznymi i zdeprawowanymi emo. To głównie piraci latający sobie od planetki do planetki zbierając niewolników i ciekawych Xenos do uprawiania bardzo niefajnych rzeczy ( ͡° ͜ʖ ͡°). Uwielbiają politykę, czyli wbijanie sobie sztyletów w plecy. Nie mają psioników, ich zbroje to ich skóra i kości, bowiem polegają na zwinności i mobilności, nawet bardziej niż ich kuzyni. Mroczni Eldarzy mimo iż mroczni nie wyznają Bogów Chaosu, jeśli już to wszelkie ich działania podyktowane są strachem przed Slaanesh.":
        "The brothers of the above-mentioned Eldar who also survive, however, are hedonistic and depraved emo. They are mostly pirates flying from planet to planet collecting slaves and interesting Xenos to do very bad things (͡ ° ͜ʖ ͡ °). They love politics, which is sticking daggers in the back. They have no psykers, their armor is their skin and bones, for they rely on agility and mobility even more than their cousins. Dark Eldars, although the dark ones do not confess to Chaos Gods, if all their actions are dictated by the fear of Slaanesh.",
      "Dominium Tau": "Dominion of Tau",
      "Prócz tego mamy jeszcze młode i prężnie rozwijające się, a także jako jedyne asymilujące, a nie eksterminujące inne gatunki Dominium Tau. To rasa walcząca dla Większego Dobra, właściwie najbardziej dobra ze wszystkich ras. Ich technologia skupia się na maskowaniach, mobilności i sile ognia - coś jak dzisiejsze wojsko. Wykorzystują pancerze bitewne - humanoidalne maszyny sterowane przez pilotów. Nie potrafią walczyć wręcz. Osobną frakcją są stworzone przez renegata z Dominium Tau tzw. Enklawy Farsighta, od nazwy buntownika. Należy pamiętać że Dominium i Enklawy są bardzo malutkie i nie mają aż takiego wpływu na sytuacje w Galaktyce ale szybko ekspandują":
        "Apart from that, we still have young and dynamically developing species, as well as the only ones that assimilate and not exterminate other species of the Tau Dominion. It is a race fighting for the Greater Good, actually the best of all races. Their technology focuses on masking, mobility and firepower - something like today's military. They use battle armor - humanoid machines controlled by pilots. They cannot fight hand-to-hand. A separate faction are the so-called Farsight's enclaves, from the name of the rebel. Remember that the Dominion and Enclaves are very tiny and do not have such an impact on the situation in the Galaxy but they expand quickly",
      Chaos: "Chaos",
      "W jego skład wchodzą jego wyznawcy, w postaci ludzi(najczęściej) czy innych obcych (np. bardzo rzadko Orkowie, czyniektórzy Eldarzy) oraz masa demonów i sił jeszcze z czasówHerezji Horusa. Są bardzo podzieleni a największym dowódcą siłjest Abaddon Profanator, zaś prawdziwi władcy tej frakcji -Mroczni Bogowie przebywają w innym wymiarze, Osnowie, gdzie sąwyłącznie emocje, uczucia i dusze, nie ma praw fizyki a konceptczasu wziął i wyszedł. Występuje tam niezliczona ilość demonów,wszystko tam jest wypaczone, czas nie istnieje itd. To dziękiOsnowie wszystkie rasy (poza Nekronami, bo używają innejtechnologii) mogą latać szybciej niż światło. Istnieje 4 bogów,docelowo 5. Tzeentch odpowiada za magię (psionizm) i knowania.Nurgle za choroby i śmierć. Khorne za przelewanie krwi. Slaaneshza hedonizm, przyjemności, czy seksualne żądze. I Malice(prawdopodobnie nie istnieje/jest niekanoniczny), wygnany przezresztę bogów bóg szaleństwa, bardzo słaby, nikt go nie lubi i wdodatku prawie nie ma armii (1 zakon, Synowie Malice i dlategojest plotka jakoby istniał - głównie dzieło fanów znającychWarhammera Fantasy, aczkolwiek nie został też zanegowany.)":
        "It consists of his followers, in the form of people (most often) or other strangers (e.g. very rarely Orcs, or some Eldar) and a mass of demons and forces from the time of the Horus Heresy. They are very divided and the greatest commander of the forces is Abaddon the Profanator, and the true rulers of this faction - the Dark Gods reside in another dimension, the Warp, where there are only emotions, feelings and souls, there are no laws of physics and the concept of time took and left. There are countless demons there, everything is warped there, time does not exist, etc. It is thanks to Osna that all races (except the Necrons, because they use different technology) can fly faster than light. There are 4 gods, ultimately 5. Tzeentch is responsible for magic (psionism) and plotting. Nurgle for disease and death. Khorne for shedding blood. Slaaneshz hedonism, pleasures, or sexual desires. And Malice (probably does not exist / is non-canonical), god of madness exiled by the other gods, very weak, nobody likes him and additionally has almost no army (1st order, Sons of Malice and therefore there is a rumor that he exists - mainly the work of fans who know Warhammer Fantasy, although not was also denied.)",
      "Warhammer Vermintide 2 to klasyczna kontynuacja, pozbawiona wielkich zmian. Jest to brutalna gra akcji nastawiona przede wszystkim na walkę na bliskim dystansie przy pomocy rozmaitych mieczy czy włóczni, choć w trakcie rozgrywki wykorzystujemy też broń o większym zasięgu, np. kuszę. Zabawa przeznaczona jest przede wszystkim do współpracy. Deweloperzy pozwalają na wspólne przeprawy czterech graczy, wcielających się w różnych, dysponujących odmiennymi zdolnościami bohaterów. Łącznie przygotowano pięciu herosów, których da się rozwijać w trzech odrębnych ścieżkach kariery, dopasowując w ten sposób styl gry pod własne upodobania. Dostępny jest krasnolud Bardin Goreksson, skrytobójczyni Kerillian, łowca głów Victor Saltzpyre, mag Sienna Fuegonasus oraz rycerz Markus Kruber. Ponadto deweloperzy poprawili system łupów. Po zakończeniu każdej misji otrzymujemy rozmaite nagrody, w tym bronie czy materiały przydające się podczas craftingu. Jedną z nowości jest system Heroic Deeds, oferujący unikalne scenariusze, poprzez zmianę składu wrogich sił, elementów otoczenia, dostępnych broni czy obiektów, które należy zrealizować.":
        "Warhammer: Vermintide 2 is a classic sequel, without big changes. It is a brutal action game focused primarily on close-range combat with various swords or spears, although we also use weapons with a greater range, such as a crossbow, during the game. The game is intended primarily for cooperation. Developers allow four players to play together, playing different heroes with different abilities. In total, five heroes have been prepared, which can be developed in three separate career paths, thus adjusting the style of the game to your liking. The dwarf Bardin Goreksson, the assassin Kerillian, the head hunter Victor Saltzpyre, the mage Sienna Fuegonasus and the knight Markus Kruber are available. In addition, the developers improved the loot system. After completing each mission, we receive various rewards, including weapons and materials that are useful during crafting. One of the new features is the Heroic Deeds system, offering unique scenarios by changing the composition of enemy forces, elements of the environment, available weapons or objects to be completed.",
      "Blood Bowl II to pełnoprawna kontynuacja wydanej w 2009 roku brutalnej gry sportowej. Ponownie mamy do czynienia z nietypową odmianą futbolu amerykańskiego. Cechą charakterystyczną produkcji jest fakt, że gra osadzona jest w realiach fantasy i posiada oficjalną licencję Games Workshop. Dzięki temu nasze drużyny złożone są z ras znanych wszystkim graczom z uniwersum kultowego Warhammera. Osią gry jest zupełnie nowa, rozbudowana kampania, pełna nagłych zwrotów akcji i ryzykownych decyzji. Tym razem wcielimy się w trenera jednej z najstarszych i najznamienitszych drużyn Starego Świata – będącej chlubą ludzi Reikland Reavers. Ogólny zarys rozgrywki pozostał jednak niezmieniony. Jako menadżer będziemy musieli ustalać skład drużyny i rozgrywać spotkania z kolejnymi przeciwnikami pamiętając o tym, że każda z ras posiada zarówno swoje mocne jak i słabe strony. Prócz odpowiedniej taktyki będziemy mogli skorzystać ze sporego arsenału broni i innych ulepszeń, dzięki którym znacznie łatwiej będzie nam przechylić szalę zwycięstwa na swoją stronę. Oprócz kampanii fabularnej, Blood Bowl II oferuje również tryb ligi, który pozwala na stworzenie od podstaw i dowolne kształtowanie własnej drużyny oraz stadionu. Podczas tworzenia gry autorzy wzięli sobie mocno do serca sugestie fanów. Dla potrzeb kontynuacji przygotowano zupełnie nowy silnik graficzny, którego możliwości znacznie wpłynęły na walory wizualne gry oraz jakość animacji. Wprowadzono też nowy system dynamicznych kamer. Nasze poczynania komentować będzie na żywo sympatyczny duet, złożony z wampira Jima Johnsona oraz ogra Boba Bifforda. Interfejs gry, transmisje meczy oraz system powtórek przygotowane zostały w charakterystycznym stylu CabalVision – oficjalnej telewizji Blood Bowl. Wzorem części pierwszej, zabawa nie ogranicza się jedynie do gry w trybie single player. Duży nacisk położono ponownie na możliwość zabawy wielu graczy, bo przecież ten właśnie element w głównej mierze zdecydował o sukcesie serii. Dzięki dokonanym zmianom, nowa odsłona gry stała się przystępniejsza dla nowicjuszy i tzw. niedzielnych graczy, lecz jednocześnie bardziej atrakcyjna i wymagająca dla wszystkich weteranów serii.":
        "Blood Bowl II is a full-fledged continuation of the brutal sports game released in 2009. Again, we are dealing with an atypical variety of American football. A characteristic feature of the production is the fact that the game is set in a fantasy setting and has an official Games Workshop license. Thanks to this, our teams are composed of races known to all players from the cult Warhammer universe. The axis of the game is a completely new, extensive campaign, full of sudden twists and risky decisions. This time we will play the role of the coach of one of the oldest and most distinguished teams of the Old World - the pride of the Reikland Reavers people. The general outline of the game, however, remained unchanged. As a manager, we will have to determine the composition of the team and play matches with other opponents, bearing in mind that each race has its own strengths and weaknesses. In addition to the right tactics, we will be able to use a large arsenal of weapons and other improvements, thanks to which it will be much easier for us to tip the scales of victory on our side. In addition to the story campaign, Blood Bowl II also offers a league mode that allows you to create from scratch and freely shape your own team and stadium. While creating the game, the authors took the fans' suggestions very seriously. For the purposes of the continuation, a completely new graphic engine was prepared, the possibilities of which significantly influenced the visual values ​​of the game and the quality of animation. A new dynamic camera system was also introduced. Our actions will be commented live by a nice duo, consisting of the vampire Jim Johnson and the ogre Bob Bifford. The game interface, match broadcasts and repetition system have been prepared in the characteristic style of CabalVision - the official Blood Bowl TV. Like the first part, the fun is not limited to single player mode. Much emphasis was again placed on the possibility of playing for many players, because it was this element that largely determined the success of the series. Thanks to the changes made, the new version of the game has become more accessible to novices and the so-called casual players, but at the same time more attractive and demanding for all veterans of the series.",
      "Total War Warhammer to dziesiąta główna odsłona słynnej serii gier strategicznych tworzonych przez brytyjski zespół Creative Assembly pod auspicjami firmy wydawniczej SEGA. Jak zwykle, rozgrywka łączy kompleksowe zarządzanie królestwem w systemie turowym na mapie świata z toczeniem widowiskowych, taktycznych bitew w czasie rzeczywistym. Tym razem jest to produkcja osadzona w fantastycznym uniwersum znanym z figurkowej gry bitewnej Warhammer Fantasy Battle, wykreowanej przez firmę Games Workshop. Omawiana pozycja stanowi początek trylogii, której poszczególne części są samodzielnymi tytułami, ale mogą też być ze sobą łączone, by tworzyć jedną 'megagrę' o potężnej zawartości.Otoczka fabularna Total War Warhammer jest osnuta wokół walki różnych ras o władzę nad Starym Światem i zmagań z nękającymi krainę demonicznymi siłami Chaosu. Twórcy oddali do naszej dyspozycji cztery grywalne frakcje ludzi z potężnego Imperium, dzikich zielonoskórych (orków, gobliny itp.), zaawansowane technologicznie krasnoludy oraz hordy nieumarłych pod wodzą książąt wampirów. W zabawie biorą udział także siły Chaosu, lecz w formie grywalnej zostały one udostępnione tylko graczom, którzy nabyli omawiany tytuł w pre-orderze albo zaopatrzyli się w później w stosowne DLC. Oprócz tego w Starym Świecie występuje szereg neutralnych frakcji.Kampania ma sandboksową strukturę, a fabułę w jej trakcie kreujemy sami, realizując oferowane nam misje. Odzwierciedlają one rozmaite „autentyczne” wydarzenia z dziejów Starego Świata i służą głównie zaopatrywaniu bohaterów w potężne artefakty lub poprawianiu kondycji naszej frakcji w inny sposób.":
        "Total War: Warhammer is the tenth major installment in the famous series of strategy games developed by the British Creative Assembly team under the auspices of the SEGA publishing company. As always, the gameplay combines comprehensive kingdom management in a turn-based system on the world map with spectacular, tactical real-time battles. This time it is a production set in a fantastic universe known from Warhammer Fantasy Battle, created by Games Workshop. This item is the beginning of a trilogy, the individual parts of which are separate titles, but can also be combined to create one 'megagra' with powerful content. The plot of Total War: Warhammer is based around the struggle of different races for power over the Old World and the struggle with the demonic forces of Chaos that haunt the land. The creators have put at our disposal four playable factions: people from the mighty Empire, wild greenskins (orcs, goblins, etc.), technologically advanced dwarves and hordes of undead led by vampire princes. The forces of Chaos also take part in the game, but in playable form they have been made available only to players who pre-ordered the title or who later acquired the appropriate DLC. In addition, there are a number of neutral factions in the Old World. The campaign has a sandbox structure, and we create the story during it ourselves, carrying out the missions offered to us. They reflect various 'authentic' events in the history of the Old World and are mainly used to supply heroes with powerful artifacts or to improve the condition of our faction in other ways.",
      "Warhammer Chaosbane jest klasycznie zrealizowanym RPG-iem akcji w stylu hack’n’slash. Oznacza to, że rozgrywkę obserwujemy w rzucie izometrycznym, a ona sama sprowadza się głównie do starć z hordami potworów za pomocą mocno zręcznościowego systemu walki, w którym równie dużą rolę jak statystyki i umiejętności bohatera odgrywa refleks gracza. Podczas zabawy przemierzamy korytarzowe lokacje, gromadzimy przedmioty oraz rozwijamy postać. Rozpoczynając przygodę, mamy cztery klasy do wyboru żołnierza Imperium, krasnoludzkiego zabójcę potworów, leśną elfkę strzelającą z łuku i władającego magią elfa wysokiego rodu. Każda z nich ma unikalne cechy wpływające na rozgrywkę.":
        "Warhammer: Chaosbane is a classic hack'n'slash action RPG. This means that we observe the gameplay in isometric projection, and it boils down mainly to clashes with hordes of monsters using a highly dexterous combat system, in which the player's reflexes play an equally important role as the hero's statistics and skills. While playing, we traverse corridor locations, collect items and develop the character. There are four classes to choose from when starting your adventure: Imperial Trooper, Dwarven Monster Slayer, Bowling Wood Elf, and High Elf with magic. Each of them has unique features that affect the gameplay.",
      "Popularność światów Warhammer wynika przede wszystkim z gier bitewnych oraz bogatych systemów fabularnych. Mroczny do bólu, zdefiniował tak naprawdę to, czym jest prawdziwy Grim Dark. Zresztą nawet motto tego uniwersum mówi, że nie będzie wesoło – In the grim, dark future, there is only war. Obecnie Warhammer 40000 przeżywa prawdziwy renesans, gdyż wcześniej to uniwersum było zbyt mroczne dla większości fanów science fiction. Powrót w glorii i chwale może wynikać z wielu elementów, między innymi zmiany władzy w Games Workshop oraz licznych działań wspierających wprowadzanie nowych osób. Może to także wynikać z prostego faktu, że rynek sam stworzył niszę – każdy film musi się kończyć happy endem, każda książka musi mieć swój wątek miłosny, w każdej grze gramy jako bohaterowie. Pluralizm męczy na dłuższą metę. I teraz pojawia się Warhammer 40000 gdzie wszyscy są co najwyżej szarzy. Ale tak naprawdę każdy jest mniej lub bardziej zły.Więc wpadłeś tutaj, mój drogi czytelniku, by znaleźć pomysł jak zacząć przygodę z mrocznym uniwersum Warhammer 40000. Czy zakup bitewniaków oraz tak zwanych Kodeksów to dobry pomysł? Zostawmy na chwilę temat że nie posiadają one (obecnie) polskiej wersji językowej, z wyjątkiem fanowskich tłumaczeń, więc bez zaawansowanego angielskiego nawet ich nie ruszycie (bardzo trudne słownictwo).W Polsce został natomiast wydany cykl Herezja Horusa, który bardzo fajnie się przyjął zarówno wśród fanów, jak i osób dopiero zaczynających przygodę z Mrocznym Milenium. Fabularnie historia opowiada o Horusie, synu imperatora, który to na czele potężnej armady poszukuje kolejne zagubione światy imperium. Świat przedstawiony w Herezji Horusa nie jest jeszcze taki mroczny, pokazuje natomiast jego genezę oraz powody dla których kwitnące imperium człowieka, stało się teokratycznym koszmarem ludzkości.Na język polski przetłumaczonych zostało już kilkanaście tomów cyklu, jednak to oryginał przez Dan Albert jest tutaj najpopularniejszy. Rozpoczyna on bardzo długi cykl, potem kontynuowany przez innych autorów. Zostawmy na razie bez komentarza ich jakość w porównaniu do pierwszych części. Herezja Horusa rozpoczyna się tomu o nazwie Czas Horusa, a wprowadzenie do niej kończy się w tomie trzecim o nazwie Galaktyka w Ogniu. Od tego też momentu zaczyna się właściwa Herezja i jest to dobry punkt by odłożyć książki i wybrać swoją armię. Mimo że książka skupia się tylko na siłach imperium, i to z wieku 30000, to świetnie ona przedstawia czym jest każda z frakcji z imperium oraz wprowadza podwaliny pod siły chaosu, które przez kolejne tysiąclecia będą nękać imperium.":
        "The popularity of the Warhammer worlds is primarily due to the battle games and rich story systems. Dark to the core, it really defined what true Grim Dark is. Anyway, even the motto of this universe says that it won't be fun - In the grim, dark future, there is only war. Currently Warhammer 40000 is experiencing a real renaissance as before this universe was too dark for most science fiction fans. The return in glory and splendor may be due to a number of elements, including a change in power at Games Workshop and numerous efforts to support the introduction of newcomers. It could also be due to the simple fact that the market itself has created a niche - every movie has to end with a happy ending, every book has to have a love plot, every game has to have us playing as characters. Pluralism gets tiring in the long run. And now comes Warhammer 40000 where everyone is grey at best. So you came here, my dear reader, to find an idea how to start your adventure with the dark universe of Warhammer 40000. Is it a good idea to buy battlebooks and so called Codexes? Let's leave aside for a moment the fact that they (currently) don't have Polish language versions, except for fan translations, so without advanced English you won't be able to use them (very difficult vocabulary). The story tells the tale of Horus, son of the emperor who at the head of a mighty armada searches for other lost worlds of the empire. The world presented in Horus' Heresy isn't so dark yet, but it shows its genesis and the reasons why the flourishing empire of man, became a theocratic nightmare of mankind.Several volumes of the series have already been translated into Polish, but it's the original by Dan Albert that is the most popular here. It begins a very long series, later continued by other authors. Let us leave for now without comment their quality in comparison with the first parts. Heresy of Horus begins with a volume called Time of Horus, and the introduction to it ends in volume three called Galaxy on Fire. This is also where the Heresy proper begins and is a good point to put the books down and pick your army. Although the book only focuses on the forces of the empire, and from the 30000th century, it does a great job of introducing what each of the factions from the empire are, and introduces the groundwork for the forces of chaos that will plague the empire for millennia to come.",
      "Warhammer 40,000 Dawn of War to pierwsza gra strategiczna rozgrywana w czasie rzeczywistym i osadzona w realiach świata Warhammer 40,000, która powstała dzięki współpracy firmy THQ (jednego z największych światowych wydawców gier) oraz studia Relic Entertainment (znanego m.in. z obu części znakomitego Homeworlda). Warhammer 40,000 to mroczny, futurystyczny świat znany z gier firmy Games Workshop. Pomimo tego, iż składa się on z milionów uniwersów, w Dawn of War autorzy postanowili skupić się wyłącznie na jednym z nich i na jednej konkretniej wojnie. W trybie dla pojedynczego gracza mamy okazję wcielić się w postać Gabriela Angelosa, dowódcę Kosmicznych Marines z Blood Ravens, który usiłuje zapobiec inwazji Orków na jego planetę. Fabuła rozwija się dzięki specjalnym przerywnikom filmowym i rzecz jasna stopniowo odkrywa przed grającym kolejne wątki i tajemnice.":
        "Warhammer 40,000 Dawn of War is the first real-time strategy game set in the realities of the Warhammer 40,000 world, which was created thanks to the cooperation of THQ (one of the world's largest game publishers) and Relic Entertainment studio (known from both parts of the excellent Homeworld ). Warhammer 40,000 is a dark, futuristic world known from Games Workshop games. Despite the fact that it consists of millions of universes, in Dawn of War the authors decided to focus only on one of them and on one particular war. In the single player mode, we have the opportunity to play the role of Gabriel Angelos, the commander of the Space Marines from Blood Ravens, who is trying to prevent the invasion of the Orcs on his planet. The plot unfolds thanks to special cutscenes and, of course, gradually reveals new threads and secrets to the players.",
      "Pierwsze kroki z WARHAMMER 40000":
        "Getting started with WARHAMMER 40000",
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: "pl",
  fallbackLng: "pl",
  keySeparator: false,

  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
